import React, { useState } from 'react';
import { View, Text, StyleSheet, TextInput, TouchableOpacity, ScrollView, Alert } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import { useApp } from '../../context/AppContext';
import ScreenContainer from '../../components/ScreenContainer';
import Colors from '../../constants/colors';
import Typography from '../../constants/typography';
import Spacing from '../../constants/spacing';

export default function PostAdScreen() {
  const navigation = useNavigation();const { addAd, isAuthenticated } = useApp();
  const [step, setStep] = useState(1);const [title, setTitle] = useState('');const [price, setPrice] = useState('');const [category, setCategory] = useState('Electronics');const [location, setLocation] = useState('Mumbai, MH');
  const submit = () => {if (!isAuthenticated) {Alert.alert('Sign in to post', 'Create an account to submit your listing.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Log In', onPress: () => navigation.navigate('Login') }]);return;}if (!title.trim() || !price.trim()) {Alert.alert('Add listing details', 'Title and price are required.');return;}addAd({ title: title.trim(), price: Number(price) || 0, category, imageUrl: 'https://picsum.photos/seed/newlisting/200/200' });Alert.alert('Ad submitted', 'Your listing is pending review.', [{ text: 'View My Ads', onPress: () => navigation.replace('MyAds') }]);};
  return <ScreenContainer noPadding><View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()}><Ionicons name="arrow-back" size={24} color={Colors.textPrimary} /></TouchableOpacity><Text style={styles.headerTitle}>Post an Ad</Text><Text style={styles.step}>Step {step}/4</Text></View><ScrollView contentContainerStyle={styles.content}>
    {step === 1 && <><Text style={styles.title}>What are you selling?</Text><Text style={styles.label}>Category</Text><View style={styles.chips}>{['Electronics', 'Fashion', 'Furniture', 'Sports'].map((c) => <TouchableOpacity key={c} onPress={() => setCategory(c)} style={[styles.chip, category === c && styles.chipOn]}><Text style={[styles.chipText, category === c && styles.chipTextOn]}>{c}</Text></TouchableOpacity>)}</View><Text style={styles.label}>Listing title</Text><TextInput value={title} onChangeText={setTitle} placeholder="e.g. iPhone 14, 128 GB" style={styles.input} /></>}
    {step === 2 && <><Text style={styles.title}>Add details & photos</Text><TouchableOpacity style={styles.photo}><Ionicons name="camera-outline" size={34} color={Colors.primary} /><Text style={styles.photoText}>Add photos (mock)</Text></TouchableOpacity><Text style={styles.label}>Condition</Text><View style={styles.chips}>{['New', 'Like New', 'Good'].map((c) => <View key={c} style={styles.chip}><Text style={styles.chipText}>{c}</Text></View>)}</View></>}
    {step === 3 && <><Text style={styles.title}>Set price and location</Text><Text style={styles.label}>Price</Text><TextInput value={price} onChangeText={setPrice} keyboardType="numeric" placeholder="0" style={styles.input} /><Text style={styles.label}>Location</Text><TextInput value={location} onChangeText={setLocation} style={styles.input} /></>}
    {step === 4 && <><Text style={styles.title}>Preview your ad</Text><View style={styles.preview}><Text style={styles.previewTitle}>{title || 'Your listing title'}</Text><Text style={styles.previewPrice}>${price || '0'}</Text><Text style={styles.previewMeta}>{category} · {location}</Text><Text style={styles.previewMeta}>Photos and listing details can be edited after submission.</Text></View></>}
  </ScrollView><View style={styles.footer}>{step > 1 && <TouchableOpacity style={styles.back} onPress={() => setStep(step - 1)}><Text style={styles.backText}>Back</Text></TouchableOpacity>}<TouchableOpacity style={styles.next} onPress={() => step === 4 ? submit() : setStep(step + 1)}><Text style={styles.nextText}>{step === 4 ? 'Submit Ad' : 'Continue'}</Text></TouchableOpacity></View></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: Spacing.md }, headerTitle: { ...Typography.heading2, color: Colors.textPrimary }, step: { ...Typography.caption, color: Colors.textSecondary }, content: { padding: Spacing.lg, paddingBottom: 110 }, title: { ...Typography.heading1, fontSize: 22, color: Colors.textPrimary, marginBottom: Spacing.lg }, label: { ...Typography.bodyBold, color: Colors.textPrimary, marginTop: Spacing.md, marginBottom: 6 }, input: { borderWidth: 1, borderColor: Colors.border, borderRadius: 10, padding: 13, ...Typography.body, color: Colors.textPrimary }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { backgroundColor: '#F1F5F9', paddingHorizontal: 13, paddingVertical: 8, borderRadius: 18 }, chipOn: { backgroundColor: Colors.primary }, chipText: { ...Typography.captionBold, color: Colors.textSecondary }, chipTextOn: { color: Colors.white }, photo: { height: 140, borderWidth: 1, borderStyle: 'dashed', borderColor: Colors.primary, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.primaryLight }, photoText: { ...Typography.bodyBold, color: Colors.primary, marginTop: 8 }, preview: { padding: Spacing.lg, borderRadius: 12, backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: Colors.border }, previewTitle: { ...Typography.heading2, color: Colors.textPrimary }, previewPrice: { ...Typography.heading1, color: Colors.primary, marginVertical: 8 }, previewMeta: { ...Typography.body, color: Colors.textSecondary, marginBottom: 4 }, footer: { position: 'absolute', bottom: 0, left: 0, right: 0, flexDirection: 'row', gap: 10, padding: Spacing.md, backgroundColor: Colors.white, borderTopWidth: 1, borderColor: Colors.border }, back: { flex: 1, alignItems: 'center', padding: 14, borderWidth: 1, borderColor: Colors.primary, borderRadius: 10 }, backText: { ...Typography.button, color: Colors.primary }, next: { flex: 2, alignItems: 'center', padding: 14, backgroundColor: Colors.primary, borderRadius: 10 }, nextText: { ...Typography.button, color: Colors.white } });